version: '3'

services:

  ewally:
    container_name:  ewally-test
    image: ewally-test
    restart: always
    build: .
    command: npm run dev
#    env_file:
#      - .env.local
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
